apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: custom-app
  template:
    metadata:
      labels:
        app: custom-app
    spec:
      containers:
      - name: custom-app
        image: custom-app:v1
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: log-volume
          mountPath: /app/logs
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: log-volume
        hostPath:
          path: /var/log/custom-app
          type: DirectoryOrCreate
      - name: config-volume
        configMap:
          name: custom-app-config
