apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: custom-app-monitor
  labels:
    release: prometheus # This matches the release label that Prometheus Operator uses
spec:
  selector:
    matchLabels:
      app: custom-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default 